### PR TITLE
Fix localization in ru/firefox/whatsnew_63.lang 

### PR DESCRIPTION
**Pull request by vtols**

### CODE REVIEW

**Comment by flodolo** [comment]
@vtols 
Thanks for your contribution, but note that translations normally happen on Pontoon.
https://pontoon.mozilla.org/ru/mozillaorg/firefox/whatsnew_63.lang/

@unghost 
Can you take a look?

**Comment by vtols** [comment]
>@vtols
Thanks for your contribution, but note that translations normally happen on Pontoon.
https://pontoon.mozilla.org/ru/mozillaorg/firefox/whatsnew_63.lang/

@flodolo
Thank you for the hint.

**Comment by vtols** [comment]
Is it a good idea to mention Pontoon here https://bedrock.readthedocs.io/en/latest/install.html#localization?

**Comment by flodolo** [comment]
Oh wait, I completely missed you opened a pull request against the [production repository](https://github.com/mozilla-l10n/bedrock-l10n/blob/master/README.md). We can't accept them.

```
If you find any localization issues, please open pull requests on the repository used for the dev server. This repository is writable only by l10n-drivers.
```

Sorry but I need to close this one. Let's wait for Alexander to see if you should use a PR or suggest directly in Pontoon.

**Comment by unghost** [comment]
@vtols  I've fixed localization in Pontoon. Thanks.

**Pull request closed without merging**
